export const SET_CAMERA_LOCATIONS = 'SET_CAMERA_LOCATIONS';
export const SET_RECORDING_LOCATIONS = 'SET_RECORDING_LOCATIONS';
export const SET_TYPE_OF_ISSUE = 'SET_TYPE_OF_ISSUE';
export const SET_LOADING = 'SET_LOADING';