export const SET_EQUIPMENT_LOCATIONS = 'SET_EQUIPMENT_LOCATIONS';
export const SET_PROJECT_LOCATIONS = 'SET_PROJECT_LOCATIONS';
export const SET_TYPE_OF_ISSUE = 'SET_TYPE_OF_ISSUE';
export const SET_LOADING = 'SET_LOADING';